[package]
name = "rustfinal"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { version = "0.11", features = ["dynamic_linking"] } 
bevy_rapier2d = "0.22"
minifb = "0.25.0"
num = "0.4.1"
rand = "0.8.5"
mki = "0.2.3"